package com.paymember.ui.components

import androidx.compose.ui.graphics.Color
import com.paymember.R

object Services {
    val fallback = ServiceBrand("fallback", Color(0xFF1F4634), Color.White, "PM")

    private val brands = mapOf(
        "netflix" to ServiceBrand("netflix", Color(0xFF0F0F10), Color(0xFFE50914), "N", R.drawable.svc_netflix),
        "spotify" to ServiceBrand("spotify", Color(0xFF0E2818), Color(0xFF1ED760), "S", R.drawable.svc_spotify),
        "disney" to ServiceBrand("disney", Color(0xFF0B1B3E), Color.White, "D+"),
        "chatgpt" to ServiceBrand("chatgpt", Color(0xFF0E2A22), Color(0xFF10A37F), "AI", R.drawable.svc_chatgpt),
        "icloud" to ServiceBrand("icloud", Color(0xFFE8F2FB), Color(0xFF1B7BE8), "iC", R.drawable.svc_icloud),
        "microsoft-365" to ServiceBrand("office", Color(0xFF22152A), Color(0xFFE8916B), "365", R.drawable.svc_microsoft_365),
        "max" to ServiceBrand("max", Color(0xFF0F1A4A), Color(0xFF7AA0FF), "M", R.drawable.svc_max),
        "prime-video" to ServiceBrand("prime", Color(0xFF0E1A28), Color(0xFF7AC4F0), "P", R.drawable.svc_prime_video),
        "amazon-prime" to ServiceBrand("amazon-prime", Color(0xFF0E1A28), Color(0xFF7AC4F0), "P", R.drawable.svc_amazon_prime),
        "apple-tv" to ServiceBrand("appletv", Color(0xFF111111), Color.White, "tv+", R.drawable.svc_apple_tv),
        "youtube-premium" to ServiceBrand("youtube", Color(0xFF1A0F10), Color(0xFFFF3D3D), "YT", R.drawable.svc_youtube_premium),
        "youtube-music" to ServiceBrand("youtube-music", Color(0xFF1A0F10), Color(0xFFFF3D3D), "YM", R.drawable.svc_youtube_music),
        "google-one" to ServiceBrand("google-one", Color(0xFFE8F2FB), Color(0xFF4285F4), "G1", R.drawable.svc_google_one),
        "apple-music" to ServiceBrand("apple-music", Color(0xFF2A1016), Color(0xFFFA243C), "AM", R.drawable.svc_apple_music),
        "amazon-music" to ServiceBrand("amazon-music", Color(0xFF0E1A28), Color(0xFF7AC4F0), "AM", R.drawable.svc_amazon_music),
        "filmin" to ServiceBrand("filmin", Color(0xFF191817), Color(0xFFE8D08C), "F"),
        "skyshowtime" to ServiceBrand("skyshowtime", Color(0xFF21163D), Color(0xFFB5AEE6), "S", R.drawable.svc_skyshowtime),
        "movistar-plus" to ServiceBrand("movistar-plus", Color(0xFF0A2D3A), Color(0xFFA6C6E8), "M+", R.drawable.svc_movistar_plus),
        "dazn" to ServiceBrand("dazn", Color(0xFF101010), Color.White, "DZ", R.drawable.svc_dazn),
        "crunchyroll" to ServiceBrand("crunchyroll", Color(0xFF2A180E), Color(0xFFF47521), "CR", R.drawable.svc_crunchyroll),
        "deezer" to ServiceBrand("deezer", Color(0xFF24112C), Color(0xFFB5AEE6), "DZ", R.drawable.svc_deezer),
        "tidal" to ServiceBrand("tidal", Color(0xFF101010), Color.White, "T", R.drawable.svc_tidal),
        "audible" to ServiceBrand("audible", Color(0xFF2A1C08), Color(0xFFE8D08C), "A", R.drawable.svc_audible),
        "uber-one" to ServiceBrand("uber-one", Color(0xFF101010), Color.White, "U", R.drawable.svc_uber_one),
        "glovo-prime" to ServiceBrand("glovo-prime", Color(0xFF28220A), Color(0xFFE8D08C), "G", R.drawable.svc_glovo_prime),
        "just-eat-plus" to ServiceBrand("just-eat-plus", Color(0xFF2D1708), Color(0xFFE8916B), "JE", R.drawable.svc_just_eat_plus),
        "carrefour-plus" to ServiceBrand("carrefour-plus", Color(0xFF0B1B3E), Color(0xFFA6C6E8), "C+", R.drawable.svc_carrefour_plus),
        "dropbox" to ServiceBrand("dropbox", Color(0xFF0E1A3A), Color(0xFFA6C6E8), "DB", R.drawable.svc_dropbox),
        "canva" to ServiceBrand("canva", Color(0xFF0A2A2A), Color(0xFFA6C6E8), "C", R.drawable.svc_canva),
        "adobe-cc" to ServiceBrand("adobe-cc", Color(0xFF2A1010), Color(0xFFE8916B), "A", R.drawable.svc_adobe_cc),
        "playstation-plus" to ServiceBrand("playstation-plus", Color(0xFF0B1B3E), Color(0xFFA6C6E8), "PS", R.drawable.svc_playstation_plus),
        "xbox-game-pass" to ServiceBrand("xbox-game-pass", Color(0xFF0E2818), Color(0xFF9CB87A), "X", R.drawable.svc_xbox_game_pass),
        "nintendo-online" to ServiceBrand("nintendo-online", Color(0xFF2A1010), Color(0xFFE8916B), "N", R.drawable.svc_nintendo_online),
        "geforce-now" to ServiceBrand("geforce-now", Color(0xFF16260C), Color(0xFF9CB87A), "GF", R.drawable.svc_geforce_now),
        "ea-play" to ServiceBrand("ea-play", Color(0xFF2A1010), Color(0xFFE8916B), "EA", R.drawable.svc_ea_play),
        "claude" to ServiceBrand("claude", Color(0xFF2A1710), Color(0xFFE8916B), "CL", R.drawable.svc_claude),
        "gemini" to ServiceBrand("gemini", Color(0xFF0B1B3E), Color(0xFFA6C6E8), "G", R.drawable.svc_gemini),
        "perplexity" to ServiceBrand("perplexity", Color(0xFF0A2A2A), Color(0xFFA6C6E8), "P", R.drawable.svc_perplexity),
        "notion-ai" to ServiceBrand("notion-ai", Color(0xFF101010), Color.White, "N", R.drawable.svc_notion_ai),
        "atresplayer" to ServiceBrand("atresplayer", Color(0xFF121212), Color(0xFFE8916B), "AT"),
        "mitele-plus" to ServiceBrand("mitele-plus", Color(0xFF151515), Color(0xFFA6C6E8), "mt+"),
        "flixole" to ServiceBrand("flixole", Color(0xFF22140A), Color(0xFFE8D08C), "Fx"),
        "mubi" to ServiceBrand("mubi", Color(0xFF101010), Color.White, "M", R.drawable.svc_mubi),
        "podimo" to ServiceBrand("podimo", Color(0xFF2A1016), Color(0xFFE4B5C5), "P"),
        "storytel" to ServiceBrand("storytel", Color(0xFF2A1710), Color(0xFFE8916B), "ST"),
        "everand" to ServiceBrand("everand", Color(0xFF101010), Color.White, "E", R.drawable.svc_everand),
        "duolingo" to ServiceBrand("duolingo", Color(0xFF16320E), Color(0xFF58CC02), "D", R.drawable.svc_duolingo),
        "babbel" to ServiceBrand("babbel", Color(0xFF111827), Color(0xFFE8D08C), "Bb"),
        "busuu" to ServiceBrand("busuu", Color(0xFF0B1B3E), Color(0xFFA6C6E8), "Bu"),
        "coursera-plus" to ServiceBrand("coursera-plus", Color(0xFF0B1B3E), Color(0xFF2A73CC), "C", R.drawable.svc_coursera_plus),
        "skillshare" to ServiceBrand("skillshare", Color(0xFF06251E), Color(0xFF00FF84), "S", R.drawable.svc_skillshare),
        "masterclass" to ServiceBrand("masterclass", Color(0xFF21130F), Color(0xFFE8916B), "MC"),
        "proton-unlimited" to ServiceBrand("proton-unlimited", Color(0xFF1B123A), Color(0xFFB5AEE6), "P", R.drawable.svc_proton_unlimited),
        "nordvpn" to ServiceBrand("nordvpn", Color(0xFF0B1B3E), Color(0xFFA6C6E8), "N", R.drawable.svc_nordvpn),
        "1password" to ServiceBrand("1password", Color(0xFF0B1B3E), Color(0xFFA6C6E8), "1P", R.drawable.svc_onepassword),
        "todoist" to ServiceBrand("todoist", Color(0xFF2A1010), Color(0xFFE8916B), "T", R.drawable.svc_todoist),
        "github-copilot" to ServiceBrand("github-copilot", Color(0xFF101010), Color.White, "GH", R.drawable.svc_github_copilot),
        "cursor" to ServiceBrand("cursor", Color(0xFF101010), Color.White, "C", R.drawable.svc_cursor),
        "midjourney" to ServiceBrand("midjourney", Color(0xFF101010), Color.White, "MJ"),
        "strava" to ServiceBrand("strava", Color(0xFF2A1208), Color(0xFFFC4C02), "S", R.drawable.svc_strava),
        "calm" to ServiceBrand("calm", Color(0xFF0B1B3E), Color(0xFFA6C6E8), "Ca"),
        "headspace" to ServiceBrand("headspace", Color(0xFF2D1708), Color(0xFFE8916B), "H", R.drawable.svc_headspace),
        "peloton" to ServiceBrand("peloton", Color(0xFF2A1010), Color(0xFFE8916B), "P", R.drawable.svc_peloton),
        "apple-arcade" to ServiceBrand("apple-arcade", Color(0xFF111111), Color.White, "A", R.drawable.svc_apple_arcade),
        "google-play-pass" to ServiceBrand("google-play-pass", Color(0xFF0B1B3E), Color(0xFFA6C6E8), "GP", R.drawable.svc_google_play_pass),
        "ubisoft-plus" to ServiceBrand("ubisoft-plus", Color(0xFF101010), Color.White, "U", R.drawable.svc_ubisoft_plus),
        "roblox-premium" to ServiceBrand("roblox-premium", Color(0xFF101010), Color.White, "R", R.drawable.svc_roblox_premium),
        "fortnite-crew" to ServiceBrand("fortnite-crew", Color(0xFF21163D), Color(0xFFB5AEE6), "F", R.drawable.svc_fortnite_crew),
        "humble-choice" to ServiceBrand("humble-choice", Color(0xFF101010), Color(0xFFE8916B), "H", R.drawable.svc_humble_choice),
        "el-pais" to ServiceBrand("el-pais", Color(0xFF0B4F8A), Color.White, "EP", R.drawable.svc_el_pais),
        "el-mundo" to ServiceBrand("el-mundo", Color(0xFF062F5F), Color.White, "EM", R.drawable.svc_el_mundo),
        "eldiario" to ServiceBrand("eldiario", Color(0xFF2A1010), Color(0xFFE8916B), "d", R.drawable.svc_eldiario),
        "la-vanguardia" to ServiceBrand("la-vanguardia", Color(0xFF172B66), Color.White, "LV", R.drawable.svc_la_vanguardia),
        "abc-premium" to ServiceBrand("abc-premium", Color(0xFF101010), Color.White, "ABC", R.drawable.svc_abc_premium),
        "el-espanol" to ServiceBrand("el-espanol", Color(0xFF2A1010), Color(0xFFE8916B), "EE", R.drawable.svc_el_espanol),
        "washington-post" to ServiceBrand("washington-post", Color(0xFF101010), Color.White, "WP", R.drawable.svc_washington_post),
        "medium" to ServiceBrand("medium", Color(0xFF101010), Color.White, "M", R.drawable.svc_medium),
        "readly" to ServiceBrand("readly", Color(0xFF08261A), Color(0xFF9CB87A), "R", R.drawable.svc_readly),
        "kindle-unlimited" to ServiceBrand("kindle-unlimited", Color(0xFF07303A), Color(0xFFA6C6E8), "KU", R.drawable.svc_kindle_unlimited),
        "ynab" to ServiceBrand("ynab", Color(0xFF062B2B), Color(0xFFA6C6E8), "Y", R.drawable.svc_ynab),
        "tradingview" to ServiceBrand("tradingview", Color(0xFF0B1B3E), Color(0xFFA6C6E8), "TV", R.drawable.svc_tradingview),
        "revolut" to ServiceBrand("revolut", Color(0xFF0B0F45), Color.White, "R", R.drawable.svc_revolut),
        "n26" to ServiceBrand("n26", Color(0xFF06251E), Color(0xFF9CB87A), "N26", R.drawable.svc_n26),
        "notion" to ServiceBrand("notion", Color(0xFF101010), Color.White, "N", R.drawable.svc_notion),
        "figma" to ServiceBrand("figma", Color(0xFF101010), Color.White, "F", R.drawable.svc_figma),
        "slack" to ServiceBrand("slack", Color(0xFF2A102B), Color(0xFFE4B5C5), "SL", R.drawable.svc_slack),
        "setapp" to ServiceBrand("setapp", Color(0xFF06251E), Color(0xFF9CB87A), "SA", R.drawable.svc_setapp)
    )

    fun brandFor(id: String): ServiceBrand = brands[id] ?: fallback.copy(mark = id.take(2).uppercase())
}
